import {create} from "zustand"
export const useStore = create((set) => ({
    city: "",
    comfirmCity: "unknown",
    condition:"unknown",
    today:"",
    tomorrow: "",
    dayThree: "",
    dayFour: "",
    dayFive: "",
    avgTemp:"unknown",
    minTemp:"unknown",
    maxTemp:"unknown",
    humidity:"unknown",
    wind:"unknown",
    setCity: (c)=>set({city: c}),
    setComfirmCity:(c)=>set({comfirmCity: c}),
    setCondition: (c)=>set({condition: c}),
    setToday: (m)=>set({today: m}),
    setTomorrow: (m)=>set({tomorrow: m}),
    setDayThree: (m)=>set({dayThree: m}),
    setDayFour: (m)=>set({dayFour: m}),
    setDayFive: (m)=>set({dayFive: m}),
    setAvgTemp: (t)=>set({avgTemp: t}),
    setMinTemp: (t)=>set({minTemp: t}),
    setMaxTemp: (t)=>set({maxTemp: t}),
    setHumidity: (h)=>set({humidity: h}),
    setWind: (w)=>set({wind: w}),
  }))